Add regression tests for setting reserved bytes
This fails now due to the way we set the reserved bytes before page
allocation

test integrity_check::test_reserved_bytes_set_before_page_allocation ... FAILED

failures:

---- integrity_check::test_reserved_bytes_set_before_page_allocation stdout ----

thread 'integrity_check::test_reserved_bytes_set_before_page_allocation' panicked at tests/integration/integrity_check.rs:1451:5:
assertion `left == right` failed: Pager should have reserved_bytes=48
  left: Some(0)
 right: Some(48)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    integrity_check::test_reserved_bytes_set_before_page_allocation